#
#  @(#) $Id
# 

#
#  Makefile のシステム依存部分（CQ_FRKSH2A用）
#


#
#  実行環境の定義
#
#      DBGENVには下記の中の１つだけを選択する。
#
#      DBGENV = ROMはROM化である（他の実行環境ではない）ことを
#      明示しているだけで、ソースコード中で参照はしていない。
#
#      共通部Makefileでデフォルトの実行環境としてGDB stubが選択される。
#      DBGENV=GDB_STUBに仮設定された状態で、このファイルが読み込まれる。
#

#DBGENV = ROM

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)

COPTS := $(COPTS)
LDFLAGS := $(LDFLAGS) -N
CDEFS := $(CDEFS) -DSH7262

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o sh726xscif.o

#
#  各セグメントの開始アドレスの定義
#

ifeq ($(DBGENV),GDB_STUB)
    TEXT_START_ADDRESS=0x1C020000
else
# ベクタテーブルの後ろ (内蔵RAM)
    TEXT_START_ADDRESS=0x1C000500
# RAM領域の先頭アドレス (内蔵RAM)
#    DATA_START_ADDRESS=0x1C000000
endif

#
#  リンカスクリプトの定義
#
ifeq ($(DBGENV),GDB_STUB)
    LDSCRIPT = $(CPU)/$(SYS)/shelf.stub.ld
else
    LDSCRIPT = $(CPU)/$(SYS)/shelf.ld
endif
