#
#  @(#) $Id: Makefile.config,v 1.1 2004/07/21 02:49:36 monaka Exp $
# 

#
#	Makefile のターゲットシステム依存部（PC/AT用）
#

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS := $(COPTS) -msoft-float
LDFLAGS := $(LDFLAGS) -msoft-float

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o start.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o pcat_com.o

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS = 0x100000
#DATA_START_ADDRESS = 0x100000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/elf_i386.ld
