#
#@(#) $Id: Makefile.config,v 1.2 2002/04/10 10:14:57 honda Exp $
# 

#
#  Makefile のプロセッサ依存 (Microblaze用)
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = mb

#
# Microblaze の gcc では -nostdlib が使用できない
#
MICROBLAZE = true

#
#  コンパイルフラグ
#
CPU_CFLAGS = -O2 -mxl-gp-opt -IC:/Xilinx/MicroBlaze/include

#
#  ライブラリ
#
CPU_LIBS = -lc 
