#
#  @(#) $Id: Makefile.config,v 1.1 2002/04/10 11:00:36 honda Exp $
# 

#
#  Makefile のシステム依存部分（Insight VirtexII用）
#

#
# マクロ定義
# 
SYS_CDEFS = 

#
#  コンパイルフラグ
#
SYS_CFLAGS = -mno-xl-soft-mul

#VirtexII以外
#SYS_CFLAGS = -mxl-soft-mul

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x0400
DATA_START_ADDRESS=0x9000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/mbelf.l

#
# libc.a の場所
#
LIBC = .

#
#  ライブラリの定義
#
SYS_LIBS = -L$(LIBC)


