#
#  @(#) $Id: Makefile.config,v 1.1 2000/11/14 16:29:31 honda Exp $
# 

#
#	Makefile のプロセッサ依存部（68040用）
#

#
#  コンパイルフラグ
#
CFLAGS := -g


#
#  コンパイラドライバの定義
#
CC = gcc
AS = gas
LD = ld
AR = ar
NM = nm
RANLIB  = ranlib
OBJCOPY = objcopy
OBJDUMP = objdump








