#
#  @(#) $Id: Makefile.config,v 1.6 2003/07/16 09:12:41 honda Exp $
# 

#
#	Makefile のターゲット依存部（Linux用）
#

#
#  開発環境名の定義
#
MARCH = Linux

#
#  カーネルに関する定義
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU) 
COPTS    := $(COPTS) -g -O2  
CDEFS    := $(CDEFS) -DOMIT_SYSTEM_TPCB

#
#  カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR) $(CONFIGDIR)/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) 
KERNEL_COBJS   := $(KERNEL_COBJS) cpu_config.o start.o

#
# makeoffset は不必要
#
OMIT_MAKEOFFSET = true
