#
#  @(#) $Id: Makefile.config,v 1.6 2003/12/01 06:29:15 honda Exp $
# 

#
#  Makefile のシステム依存部分（Optimize EZARM7ボード用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=arm7tdmi
LDFLAGS  := $(LDFLAGS) -mcpu=arm7tdmi  -N
DBGENV   := 
#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o lpc2214.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/ezarm7.ld


#
#  ターゲットボード依存の定義
#
COPTS   := $(COPTS) -mlittle-endian
LDFLAGS := $(LDFLAGS) -mlittle-endian 
TEXT_START_ADDRESS=0x0000003c
