#
#  @(#) $Id: Makefile.config,v 1.1 2025/11/04 17:03:19 roi Exp $
# 

#
#  Makefile のシステム依存部分（TRION T120-BGA324用）
#

#
#  開発環境名の定義
#
MARCH = riscv32

#
#  実行環境の定義
#
ifeq ($(DBGENV),GDB_STUB)
DBGENV = RAM
endif
ifeq ($(DBGENV),)
DBGENV = RAM
endif

#
#  FPGA情報の取り込み
#
include $(CONFIGDIR)/$(CPU)/$(SYS)/soc.mk

RVMARCH := rv32im
MABI := ilp32

ifeq ($(RV_A),yes)
	RVMARCH := $(RVMARCH)a
else
    ifeq ($(RV_C),yes)
	    RVMARCH := $(RVMARCH)a
    endif
endif

ifeq ($(RV_C),yes)
	RVMARCH := $(RVMARCH)c
endif

ifeq ($(RV_F),yes)
	RVMARCH := $(RVMARCH)f
    ifeq ($(RV_D),yes)
	    MABI := $(MABI)d
	else
	    MABI := $(MABI)f
    endif
	CDEFS := $(CDEFS) -DUSE_FPU
endif

ifeq ($(RV_D),yes)
	RVMARCH := $(RVMARCH)d
endif

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS    := $(COPTS) -march=$(RVMARCH) -mabi=$(MABI) -mcmodel=medany -nostdlib
CDEFS    := $(CDEFS) -DOMIT_CSR_MISA -DDBGENV=$(DBGENV)
LDFLAGS  := $(LDFLAGS) -nostdlib -nostartfiles

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o

#
#  システムサービスに関する定義
#
STASK_DIR := $(STASK_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
STASK_COBJS := $(STASK_COBJS) hw_serial.o

#
#  各セグメントの開始アドレスの定義
#
ifeq ($(DBGENV),ROM)
TEXT_START_ADDRESS = F9000000
else
TEXT_START_ADDRESS = F9002000
endif

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/riscv32elf.ld

