#
#		Makefileのプロセッサ依存部（Cortex-M3/M4/M7用）
#

#
#  開発環境名の定義
#
MARCH = armv7m

#
#  ターゲットアーキテクチャの定義
#
TARGET = arm-none-eabi

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU) 
COPTS := $(COPTS) -O2 
CDEFS := $(CDEFS) -DOMIT_SYSTEM_TPCB -DOMIT_VXCFG_INT
LDFLAGS := $(LDFLAGS) -nostdlib -nostartfiles

#
#  FPUの設定
#
ifeq ($(FPU_ABI),)
FPU_ABI = softfp
endif
ifeq ($(FPU_ARCH_OPT),)
FPU_ARCH_OPT = fpv4-sp-d16
endif
ifeq ($(FPU_USAGE),)
FPU_USAGE = FPCCR_NO_PRESERV
endif

COPTS := $(COPTS) -mfloat-abi=$(FPU_ABI) -mfpu=$(FPU_ARCH_OPT)
CDEFS := $(CDEFS) -DFPU_ENABLE -DFPCCR_INIT=$(FPU_USAGE)
ifeq ($(FPU_USAGE),FPU_NO_PRESERV)
else
CDEFS := $(CDEFS) -DCONTROL_FPU_REGISTERS
endif

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
        -O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
