#
#  @(#) $Id: Makefile.config,v 1.3 2002/04/10 12:08:17 honda Exp $
# 

#
#	Makefile のターゲットシステム依存部（PC/AT用）
#

#
#  コンパイルフラグ
#
CFLAGS := $(CFLAGS) -msoft-float
LDFLAGS := $(LDFLAGS) -msoft-float

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS = 0x100000
#DATA_START_ADDRESS = 0x100000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/elf_i386.ld
