#
#  @(#) $Id: Makefile.config,v 1.2 2001/10/22 02:16:43 imai Exp $
#

#
#  Makefile のシステム依存部分
#     京都マイクロコンピュータ(株) KZ-SH1-01
#     CQ出版 RISC評価キット SH-1
#    兼用
#

#
#  コンパイルフラグ
#
#　　ICEを用いる場合
#  　　・実機とICEのクロック周波数の違いを吸収
#  　　・dataセグメントの扱いに不具合のある一部のICEに対応
#　　　　（アドレスLMAにダウンロードすべきデータをVMAに
#　　　　　ダウンロードしてしまう）
#
#　　　make USE_ICE=true
#　　とする。

ifeq ($(USE_ICE),true)
    SYS_CDEFS = -DCONFIG_20MHZ -DUSE_ICE
else
#   京都マイクロコンピュータ(株) KZ-SH1-01の場合
    SYS_CDEFS = -DCONFIG_20MHZ
#   CQ出版 RISC評価キット SH-1の場合
#   SYS_CDEFS = -DCONFIG_19MHZ
endif


#
#  各セグメントの開始アドレスの定義
#
# テキストセクションの先頭番地
# ベクタテーブルの後ろ
TEXT_START_ADDRESS=0x00000400

# RAM領域の先頭アドレス
# エリア3：外部メモリ
DATA_START_ADDRESS=0x0a000000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld
