#
#  TOPPERS/JSP Kernel
#      Toyohashi Open Platform for Embedded Real-Time Systems/
#      Just Standard Profile Kernel
#
#  Copyright (C) 2000,2001 by Embedded and Real-Time Systems Laboratory
#                              Toyohashi Univ. of Technology, JAPAN
#  Copyright (C) 2001 by Industrial Technology Institute,
#                              Miyagi Prefectural Government, JAPAN
#
#  上記著作権者は，以下の条件を満たす場合に限り，本ソフトウェア（本ソ
#  フトウェアを改変したものを含む．以下同じ）を使用・複製・改変・再配
#  布（以下，利用と呼ぶ）することを無償で許諾する．
#  (1) 本ソフトウェアをソースコードの形で利用する場合には，上記の著作
#      権表示，この利用条件および下記の無保証規定が，そのままの形でソー
#      スコード中に含まれていること．
#  (2) 本ソフトウェアをバイナリコードの形または機器に組み込んだ形で利
#      用する場合には，次のいずれかの条件を満たすこと．
#    (a) 利用に伴うドキュメント（利用者マニュアルなど）に，上記の著作
#        権表示，この利用条件および下記の無保証規定を掲載すること．
#    (b) 利用の形態を，別に定める方法によって，上記著作権者に報告する
#        こと．
#  (3) 本ソフトウェアの利用により直接的または間接的に生じるいかなる損
#      害からも，上記著作権者を免責すること．
#
#  本ソフトウェアは，無保証で提供されているものである．上記著作権者は，
#  本ソフトウェアに関して，その適用可能性も含めて，いかなる保証も行わ
#  ない．また，本ソフトウェアの利用により直接的または間接的に生じたい
#  かなる損害に関しても，その責任を負わない．
#
#  @(#) $Id: Makefile.config,v 1.1 2001/05/04 09:11:11 imai Exp $
#

#
#  Makefile のシステム依存部分
#     京都マイクロコンピュータ(株) KZ-SH1-01
#     CQ出版 RISC評価キット SH-1
#    兼用
#
ifeq ($(USE_ICE),true)
    CDEFS := $(CDEFS) -DUSE_ICE -DCONFIG_20MHZ
else
#   京都マイクロコンピュータ(株) KZ-SH1-01の場合
    CDEFS := $(CDEFS) -DCONFIG_20MHZ
#   CQ出版 RISC評価キット SH-1の場合
#   CDEFS := $(CDEFS) -DCONFIG_19MHZ
endif

#
#  各セグメントの開始アドレスの定義
#

# ベクタテーブルの後ろ
TEXT_START_ADDRESS=0x00000400

# RAM領域の先頭アドレス
# エリア3：外部メモリ
DATA_START_ADDRESS=0x0a000000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld
