#
#  @(#) $Id: Makefile.config,v 1.5 2003/12/18 06:34:40 honda Exp $
# 

#
#  Makefile のシステム依存部分
#     京都マイクロコンピュータ(株) KZ-SH1-01
#     CQ出版 RISC評価キット SH-1
#    兼用
#


#
#  実行環境の定義
#
#　　　ROM化である（他の実行環境ではない）ことを明示しているだけで、
#　　　ソースコード中で参照はしていない。
#
#      DBGENVには下記の中の１つだけを選択する。
#　　　どちらも選択しなければ、共通部でデフォルトの実行環境GDBが
#　　　選択される

DBGENV = ROM
#DBGENV = MULTI_STACK

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)

COPTS := $(COPTS)
LDFLAGS := $(LDFLAGS)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o sh1sci.o

#
#  マクロ定義オプション
#
#　　ICEを用いる場合
#  　　・実機とICEのクロック周波数の違いを吸収

ifeq ($(DBGENV),MULTI_STACK)
    CDEFS := -DCONFIG_20MHZ $(CDEFS)
else
#   京都マイクロコンピュータ(株) KZ-SH1-01の場合
    CDEFS := -DCONFIG_20MHZ $(CDEFS)
#   CQ出版 RISC評価キット SH-1の場合
#     上の行をコメントアウトして、下の行を有効にする
#   CDEFS := -DCONFIG_19MHZ $(CDEFS)
endif



#
#  各セグメントの開始アドレスの定義
#
# テキストセクションの先頭番地
# ベクタテーブルの後ろ
TEXT_START_ADDRESS=0x00000400

# RAM領域の先頭アドレス
# エリア3：外部メモリ
DATA_START_ADDRESS=0x0a000000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld
