#
# 

#
#  Makefile のシステム依存部分（CQ-FRK-NXP-ARM用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS) \
	-I$(CONFIGDIR)/$(CPU)/_common_lpc2388 \
	-I$(SRCDIR)/pdic/simple_sio
COPTS    := $(COPTS) -mcpu=arm9tdmi -D__RUN_ON_SRAM
LDFLAGS  := $(LDFLAGS) -mcpu=arm9tdmi  -N 

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS) \
	:$(CONFIGDIR)/$(CPU)/_common_lpc2388 \
	:$(SRCDIR)/pdic/simple_sio
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) chip_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) chip_config.o sys_config.o chip_mmr.o lpc2388uart.o

#
#  リンカスクリプトの定義
#

# Flash ROMで実行するコード
#LDSCRIPT = $(CPU)/_common_lpc2388/lpc2388.ld

SRAMで実行するコード。ロードする前に	MEMMAP = 0x02;でSRAMをベクトル領域にマップすること
LDSCRIPT = $(CPU)/_common_lpc2388/lpc2388_sram.ld


#
#  ターゲットボード依存の定義
#

#  LPC2388用
COPTS   := $(COPTS) -mlittle-endian   
LDFLAGS := $(LDFLAGS) -mlittle-endian 


