#
#  @(#) $Id: Makefile.config,v 1.1 2000/11/14 14:44:14 hiro Exp $
# 

#
#	Makefile のプロセッサ依存部（68040用）
#

#
#  コンパイルフラグ
#
CFLAGS := $(CFLAGS) -O2 -m68020-40

#
#  ターゲットアーキテクチャの定義
#
ARCH = m68k-unknown-elf

#
#  ディレクトリの定義
#
TOPDIR = /usr/local/$(ARCH)
LIBDIR = $(TOPDIR)/lib
SFLIBDIR = $(LIBDIR)/msoft-float
INCDIR = $(TOPDIR)/include

#
#  コンパイラドライバの定義
#
CC = $(ARCH)-gcc
AS = $(ARCH)-as
LD = $(ARCH)-ld
AR = $(ARCH)-ar
NM = $(ARCH)-nm
RANLIB = $(ARCH)-ranlib
OBJCOPY = $(ARCH)-objcopy
OBJDUMP = $(ARCH)-objdump
