#
#  @(#) $Id: Makefile.config,v 1.4 2001/10/08 08:46:54 hiro Exp $
# 

#
#	Makefile のプロセッサ依存部（M68040用）
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = m68k-unknown-elf

#
#  コンパイルフラグ
#
CPU_CFLAGS = -O2 -m68020-40
