#
#  @(#) $Id: Makefile.config,v 1.3 2001/02/23 19:01:11 honda Exp $
# 

#
#  Makefile のシステム依存部分（DVESH3用）
#

#
#  コンパイルフラグ
#  モード0or7で
#  CPU供給クロックとして
#  30MHz,60MHzを選択する
#
#CDEFS := $(CDEFS) -DCONFIG_30MHZ
CDEFS := $(CDEFS) -DCONFIG_60MHZ 

#
# ビックエンディアン
# 
CFLAGS := $(CFLAGS) -mb 

LDFLAGS := $(LDFLAGS) 

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x0C001000
DATA_START_ADDRESS=0x0C080000


#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld




