#
#  @(#) $Id: Makefile.config,v 1.7 2001/10/19 13:56:51 honda Exp $
# 

#
#  Makefile のシステム依存部分（DVESH3用）
#

#
#  コンパイルフラグ
#  モード0or7で
#  CPU供給クロックとして
#  30MHz,60MHzを選択する
#
SYS_CDEFS = -DCONFIG_60MHZ  
#SYS_CDEFS = -DCONFIG_30MHZ 

#
# ビックエンディアン
# 
SYS_CFLAGS = -mb 

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x0C001000
DATA_START_ADDRESS=0x0C080000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld




