#
#  @(#) $Id: Makefile.config,v 1.1 2000/11/14 16:30:22 honda Exp $
# 

#
#  Makefile のシステム依存部分（DVESH3用）
#

#
#  コンパイルフラグ
#  モード0or7で
#  CPU供給クロックとして
#  30MHz,60MHzを選択する
#
#CFLAGS := $(CFLAGS) -DCONFIG_30MHZ
CFLAGS := $(CFLAGS) -DCONFIG_60MHZ 

#
# ビックエンディアン
# 割り込み要因レジスタがSH7709シリーズとは異なり
# INTEVTを使うためコンパイルフラグで分ける
# 
CFLAGS := $(CFLAGS) -mb -DCONFIG_SH7708

LDFLAGS := $(LDFLAGS) 

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x0C001000
DATA_START_ADDRESS=0x0C080000


#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld




