#
#  @(#) $Id: Makefile.config,v 1.2 2010/01/02 15:14:24 roi Exp $
# 

#
#  Makefile のシステム依存部分（MINDSTROMSNXT用）
#

#  拡張NXTファームウェア(RXE),nxtBIOS(ROM)
DBGENV := RXE
#DBGENV := ROM

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=arm7tdmi -Wa,--gstabs -mthumb -mthumb-interwork -ffunction-sections -fdata-sections
LDFLAGS  := $(LDFLAGS) -mcpu=arm7tdmi -mthumb -mthumb-interwork -N 

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o mindstormsnxt.o

#
#  システムサービスに関する定義
#
STASK_DIR := $(STASK_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
ifeq ($(DBGENV),ROM)
else
STASK_ASMOBJS := $(STASK_ASMOBJS) nxt_binary_header.o nxt_entry_point.o
endif

#
#  リンカスクリプトの定義
#
ifeq ($(DBGENV),ROM)
LDSCRIPT = $(CPU)/$(SYS)/mindstormsnxt_rom.ld
else
LDSCRIPT = $(CPU)/$(SYS)/mindstormsnxt_rxe.ld
endif

#
#  ターゲットボード依存の定義
#

#  INTEGRATOR用
COPTS   := $(COPTS) -D_MINDSTORMSNXT_ -DLOG_AFTERINIT -mlittle-endian
ifeq ($(DBGENV),ROM)
COPTS   := $(COPTS) -DNXTBIOS
endif
LDFLAGS := $(LDFLAGS) -mlittle-endian 

