#
#  @(#) $Id: Makefile.config,v 1.1 2025/12/25 14:58:11 roi Exp $
# 

#
#  Makefile のシステム依存部分（OM13058用）
#

#
#  実行環境の定義
#
ifeq ($(DBGENV),GDB_STUB)
DBGENV = RAM
endif
ifeq ($(DBGENV),)
DBGENV = RAM
endif

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=cortex-m0plus -mthumb -mlittle-endian -nostartfiles
CDEFS    := $(CDEFS) -DDBGENV=$(DBGENV) -DTOPPERS_$(DBGENV)_EXEC
LDFLAGS  := $(LDFLAGS) -mlittle-endian -nostartfiles

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) 
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o

#
#  システムサービスに関する定義
#
STASK_DIR := $(STASK_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
STASK_ASMOBJS := $(STASK_ASMOBJS) 
STASK_COBJS := $(STASK_COBJS) hw_serial.o om13058.o

#
#  リンカスクリプトの定義
#
ifeq ($(DBGENV),RAM)
LDSCRIPT = $(CPU)/$(SYS)/nxplpc11u6x_ram.ld
else
LDSCRIPT = $(CPU)/$(SYS)/nxplpc11u6x_rom.ld
endif

