#
#  @(#) $Id: Makefile.config,v 1.5 2003/06/04 05:41:16 hiro Exp $
# 

#
#	Makefile のターゲットシステム依存部（M52235EVB用）
#
#

#  実行環境の定義
#
#      DBGENVには下記の中の１つだけを選択する。
#
#　　　DBGENV = ROMはROM化である（他の実行環境ではない）ことを
#　　　明示しているだけで、ソースコード中で参照はしていない。
#
#　　　共通部Makefileでデフォルトの実行環境としてGDB stubが選択される。
#　　　DBGENV=GDB_STUBに仮設定された状態で、このファイルが読み込まれる。
#　　　

#DBGENV = ROM
#DBGENV = MULTI_STACK

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS) 
COPTS := $(COPTS) 
LDFLAGS := $(LDFLAGS) 
CDEFS := $(CDEFS) -DM52235

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o mcfuart.o


#
#  各セグメントの開始アドレスの定義
#

ifeq ($(DBGENV),GDB_STUB)
# ベクタテーブルの後ろ
    TEXT_START_ADDRESS=0x00005000
# RAM領域の先頭アドレス
    DATA_START_ADDRESS=0x20003000
else
# ベクタテーブルの後ろ
    TEXT_START_ADDRESS=0x00000430
# RAM領域の先頭アドレス
    DATA_START_ADDRESS=0x20000000
endif

#
#  リンカスクリプトの定義
#
ifeq ($(DBGENV),GDB_STUB)
    LDSCRIPT = $(CPU)/$(SYS)/cfv2elf.stub.ld
else
    LDSCRIPT = $(CPU)/$(SYS)/cfv2elf.ld
endif
