#
#  @(#) $Id: Makefile.config,v 1.1 2004/07/21 02:49:36 monaka Exp $
# 

#
#  Makefile のプロセッサ依存部（IA32用）
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = i386-pizzafactory-elf

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)
COPTS := $(COPTS) -Wall -g

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o

#
#  スタートアップモジュールに関する定義
#
#START_OBJS = start.o
START_OBJS =

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
