#
#@(#) $Id: Makefile.config,v 1.4 2001/11/08 21:28:33 honda Exp $
# 

#
#  Makefile のプロセッサ依存 (ARM7TDMI用)
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = arm-elf

#
#  コンパイルフラグ
#
CPU_CFLAGS =  -mcpu=arm7tdmi -O2 -Wall
