#
#  @(#) $Id: Makefile.config,v 1.3 2001/11/08 21:28:19 honda Exp $
# 

#
#  Makefile のシステム依存部分（Evaluator-7T用）
#

#
#  コンパイルフラグ
#
SYS_CFLAGS = -mlittle-endian 

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x00008000
DATA_START_ADDRESS=0x0003A000



#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/armelf.ld






