#
#@(#) $Id: Makefile.config,v 1.4 2005/03/11 07:37:57 honda Exp $
# 

#
#  Makefile のプロセッサ依存 (Nios2用)
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = nios2-elf

#
#  オブジェクトファイル名の拡張子の設定
#
OBJEXT = elf


#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)

#Stratix
#COPTS   := $(COPTS) -g -O2  

#Cyclone
COPTS    := $(COPTS)   -O2  -mno-hw-mul -g


#
#  カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR) $(SRCDIR)/config/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) cpu_config.o nios2.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
