#
#  @(#) $Id: Makefile.config,v 1.1 2026/03/11 16:18:31 roi Exp $
# 

#
#  Makefile のシステム依存部分（NE10-Nano用）
#

#
#  実行環境の定義
#
ifeq ($(DBGENV),GDB_STUB)
DBGENV = RAM
endif
ifeq ($(DBGENV),)
DBGENV = RAM
endif

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=cortex-a9 -mhard-float -mfloat-abi=softfp -mfpu=neon -mlittle-endian -nostartfiles
CDEFS    := $(CDEFS) -DDBGENV=$(DBGENV) -DTOPPERS_$(DBGENV)_EXEC -DSUPPORT_VFPv3_NEON
LDFLAGS  := $(LDFLAGS) -mlittle-endian -nostartfiles

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o pl310.o hw_interpro.o

#
#  システムサービスに関する定義
#
STASK_DIR := $(STASK_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
STASK_ASMOBJS := $(STASK_ASMOBJS) 
STASK_COBJS := $(STASK_COBJS) hw_serial.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/socfpga.ld

TEXT_START_ADDRESS = 0x01000000

