#
#  @(#) $Id: Makefile.config,v 1.3 2025/05/27 09:44:05 roi Exp $
# 

#
#  Makefile のシステム依存部分（AT91SAM7S用）
#

#
#  実行環境の定義
#
#      DBGENVには下記の中の１つだけを選択する。
#
#      DBGENV = ROMはROM化である（他の実行環境ではない）ことを
#      明示しているだけで、ソースコード中で参照はしていない。
#
#      共通部Makefileでデフォルトの実行環境としてGDB stubが選択される。
#      DBGENV=GDB_STUBに仮設定された状態で、このファイルが読み込まれる。
#

DBGENV = ROM

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=arm7tdmi -Wa,--gstabs 
LDFLAGS  := $(LDFLAGS) -mcpu=arm7tdmi  -N 

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o at91sam7s.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/at91sam7s.ld


#
#  ターゲットボード依存の定義
#

#  INTEGRATOR用
ifeq ($(AT91SAM7S_TYPE),at91sam7s256)
COPTS   := $(COPTS) -D__AT91SAM7S256__ -mlittle-endian
else
COPTS   := $(COPTS) -D__AT91SAM7S128__ -mlittle-endian
endif
LDFLAGS := $(LDFLAGS) -mlittle-endian 
TEXT_START_ADDRESS=0x00000040
ifeq ($(DBGENV),RAM)
else
DATA_START_ADDRESS=0x00200000
COPTS := $(COPTS) -DVECTOR_IN_ROM
endif
