#
#  @(#) $Id: Makefile.config,v 1.2 2006/06/11 11:14:24 roi Exp $
# 

#
#  Makefile のシステム依存部分（AT91SAM7S用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=arm7tdmi -Wa,--gstabs 
LDFLAGS  := $(LDFLAGS) -mcpu=arm7tdmi  -N 

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o at91sam7s.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/at91sam7s.ld


#
#  ターゲットボード依存の定義
#

#  INTEGRATOR用
ifeq ($(AT91SAM7S_TYPE),at91sam7s128)
COPTS   := $(COPTS) -D__AT91SAM7S128__ -mlittle-endian
else
COPTS   := $(COPTS) -D__AT91SAM7S256__ -mlittle-endian
endif
LDFLAGS := $(LDFLAGS) -mlittle-endian 
TEXT_START_ADDRESS=0x00000040
ifdef VECTOR_IN_ROM
DATA_START_ADDRESS=0x00200000
COPTS := $(COPTS) -DVECTOR_IN_ROM
endif
