#
#@(#) $Id: Makefile.config,v 1.2 2001/10/22 02:16:43 imai Exp $
# 

#
#  Makefile のプロセッサ依存 (SH1用)
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = sh-hitachi-elf

#
#  コンパイルフラグ
#
CPU_CFLAGS = -m1 -O2 -mhitachi -Wall
CPU_CDEFS = -DLABEL_ASM
