#
#  @(#) $Id: Makefile.config,v 1.5 2003/12/18 06:34:40 honda Exp $
# 

#
#	Makefile のプロセッサ依存部（SH1用）
#

#
#  ターゲットアーキテクチャの定義
#
# for GNUWing
#TARGET = sh-elf

TARGET = sh-hitachi-elf

#
#  コンパイルオプション
#
# 実行すべきタスクがないときの省電力モードへの移行を
# 省略する場合はCOPTSに
#   -DOMIT_POWER_CONTROL
# を追加する。
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)
COPTS := $(COPTS) -Wall -g -O2 -m1 -mhitachi -DLABEL_ASM 


#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
