#
#@(#) $Id: Makefile.config,v 1.4 2001/05/07 10:33:43 takayuki Exp $
# 

#
#  Makefile のプロセッサ依存 (V850用)
#

#
#  コンパイルフラグ
#
CFLAGS := $(CFLAGS) -mv850 -O2 -Wall -ffixed-r2

#
#  ターゲットアーキテクチャの定義
#
ARCH = v850-nec-elf

#
#  ディレクトリの定義
#
TOPDIR = /usr/local/v850-nec-elf
LIBDIR = $(TOPDIR)/lib
INCDIR = $(TOPDIR)/include


#
#  コンパイラドライバの定義
#
ARCH = v850-nec-elf
CC = $(ARCH)-gcc
AS = $(ARCH)-as
LD = $(ARCH)-ld
AR = $(ARCH)-ar
NM = $(ARCH)-nm
RANLIB = $(ARCH)-ranlib
OBJCOPY = $(ARCH)-objcopy
OBJDUMP = $(ARCH)-objdump


#
#  デフォルトコンパイルルールの定義
#
%.o: %.c
	$(CC) -c $(CFLAGS) $<

%.s: %.c
	$(CC) -S $(CFLAGS) $<

%.o: %.S
	$(CC) -c $(CFLAGS) $<
