#
#  @(#) $Id: Makefile.config,v 1.3 2000/11/24 12:42:54 hiro Exp $
# 

#
#	Makefile のプロセッサ依存部（V850用）
#

#
#  コンパイルフラグ
#
CFLAGS := $(CFLAGS) -O2

#
#  ターゲットアーキテクチャの定義
#
ARCH = v850-nec-elf

#
#  ディレクトリの定義
#
TOPDIR = /usr/local/$(ARCH)
LIBDIR = $(TOPDIR)/lib
SFLIBDIR = $(LIBDIR)/msoft-float
INCDIR = $(TOPDIR)/include

#
#  コンパイラドライバの定義
#
CC = $(ARCH)-gcc
AS = $(ARCH)-as
LD = $(ARCH)-ld
AR = $(ARCH)-ar
NM = $(ARCH)-nm
RANLIB = $(ARCH)-ranlib
OBJCOPY = $(ARCH)-objcopy
OBJDUMP = $(ARCH)-objdump
