#
#  @(#) $Id: Makefile.config,v 1.1 2000/11/14 16:30:22 honda Exp $
# 

#
#  Makefile のシステム依存部分（CARD-E09A用）
#

#
#  エンディアン
#



#
#  コンパイルフラグ
#  リトルエンディアン
#
CFLAGS := -ml $(CFLAGS)  
LDFLAGS := $(LDFLAGS) 


#
#  各セグメントの開始アドレスの定義
#  stubを使う場合はstubの分下にずらす
#
TEXT_START_ADDRESS=0x0C033000
DATA_START_ADDRESS=0x0C123000


#
# スタブを使わずCFからブートする場合の設定
#

#TEXT_START_ADDRESS=0x0C030000
#DATA_START_ADDRESS=0x0C120000




#
#   リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shlelf.ld


#
#  スタートアップモジュールに関する定義
#
ifeq ($(WITH_STUB),false)
START_OBJS = pce_header.o  start.o
endif



