#
#  @(#) $Id: Makefile.config,v 1.4 2001/11/13 11:48:22 honda Exp $
# 

#
#  Makefile のシステム依存部分（CARD-E09A用）
#

#
# マクロ定義
# 
SYS_CDEFS = 

#
#  コンパイルフラグ
#  リトルエンディアン
#
SYS_CFLAGS = -ml 

#
#  各セグメントの開始アドレスの定義
#  GDB Stub を使う場合は GDB Stubが使用する分下にずらす
#
ifeq ($(GDB_STUB),true)
     TEXT_START_ADDRESS=0x0C033000
     DATA_START_ADDRESS=0x0C123000
else
# GDB Stub を使わずCFからブートする場合の設定
     TEXT_START_ADDRESS=0x0C030000
     DATA_START_ADDRESS=0x0C120000
endif

#
#   リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shlelf.ld

#
#  スタートアップモジュールに関する定義
#
ifeq ($(GDB_STUB),false)
START_OBJS = pce_header.o  start.o
endif



