#
#@(#) $Id: Makefile.config,v 1.5 2001/10/19 05:47:35 honda Exp $
# 

#
#  Makefile のプロセッサ依存 (SH用)
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = sh-hitachi-elf

#
#  コンパイルフラグ
#
CPU_CFLAGS = -m3 -O2
CPU_CDEFS = -DLABEL_ASM 
