#
#@(#) $Id: Makefile.config,v 1.2 2001/03/27 07:16:49 honda Exp $
# 

#
#  Makefile のプロセッサ依存 (SH用)
#

#
#  コンパイルフラグ
#
CFLAGS := $(CFLAGS) -m3 -mhitachi -O2 -Wall

#
#  ターゲットアーキテクチャの定義
#
ARCH = sh-hitachi-elf

#
#  ディレクトリの定義
#
TOPDIR = /usr/local/sh-hitachi-elf
LIBDIR = $(TOPDIR)/lib
#SFLIBDIR = $(LIBDIR)/msoft-float
INCDIR = $(TOPDIR)/include




#
#  コンパイラドライバの定義
#
ARCH = sh-hitachi-elf
CC = $(ARCH)-gcc
AS = $(ARCH)-as
LD = $(ARCH)-ld
AR = $(ARCH)-ar
NM = $(ARCH)-nm
RANLIB = $(ARCH)-ranlib
OBJCOPY = $(ARCH)-objcopy
OBJDUMP = $(ARCH)-objdump


#
#  デフォルトコンパイルルールの定義
#
%.o: %.c
	$(CC) -c $(CFLAGS) $<

%.s: %.c
	$(CC) -S $(CFLAGS) $<

%.o: %.S
	$(CC) -c $(CFLAGS) $<







