#
#  @(#) $Id: Makefile.config,v 1.3 2000/11/24 12:42:57 hiro Exp $
# 

#
#	Makefile のターゲットシステム依存部（uPD703000用）
#

#
#  コンパイルフラグ
#
CFLAGS := $(CFLAGS)
LDFLAGS := $(LDFLAGS) -msoft-float

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/v850elf.ld
