#
#  @(#) $Id: Makefile.config,v 1.1 2025/11/11 16:29:05 roi Exp $
# 

#
#  Makefile のシステム依存部分（Cygwin用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) 
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o

