#
#  @(#) $Id: Makefile.config,v 1.2 2001/05/02 09:37:23 honda Exp $
# 

#
#  Makefile のシステム依存部分（MS7709ASE01用）
#



#
#  コンパイルフラグ
#  リトルエンディアン
#
CFLAGS := $(CFLAGS) -ml

LDFLAGS := $(LDFLAGS) 

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x0C001000
DATA_START_ADDRESS=0x0C100000




#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shlelf.ld






