#
#  @(#) $Id: Makefile.config,v 1.8 2001/10/20 15:39:15 honda Exp $
# 

#
#  Makefile のシステム依存部分（MS7709ASE01用）
#

#
# マクロ定義
# 
SYS_CDEFS =

#
#  コンパイルフラグ
#  リトルエンディアン
#
SYS_CFLAGS = -ml

#
#  各セグメントの開始アドレスの定義
#
ifeq ($(GDB_STUB),true)
     TEXT_START_ADDRESS=0x0C003000
     DATA_START_ADDRESS=0x0C100000
else
ifeq ($(PARTNER_J),true)
     TEXT_START_ADDRESS=0x0C000000
     DATA_START_ADDRESS=0x0C100000
endif
endif

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shlelf.ld





