#
#  @(#) $Id: Makefile.config,v 1.2 2002/04/06 12:23:01 honda Exp $
# 

#
#  Makefile のプロセッサ依存部（i386用）
#

#
#  コンパイルフラグ
#
CFLAGS := $(CFLAGS) -O2

#
#  ターゲットアーキテクチャの定義
#
TARGET = i386-elf

#
#  ディレクトリの定義
#
#TOPDIR = /usr/local/$(ARCH)
#LIBDIR = $(TOPDIR)/lib
#SFLIBDIR = $(LIBDIR)/msoft-float
#INCDIR = $(TOPDIR)/include
