#
#  @(#) $Id: Makefile.config,v 1.1 2025/11/04 11:19:05 roi Exp $
# 

#
#  Makefile のシステム依存部分（Raspberry Pi Pico2 RISC-V用）
#

#
#  開発環境名の定義
#
MARCH = riscv32

#
#  実行環境の定義
#
ifeq ($(DBGENV),GDB_STUB)
DBGENV = RAM
endif
ifeq ($(DBGENV),)
DBGENV = RAM
endif

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS    := $(COPTS) -march=rv32imac -mabi=ilp32 -mcmodel=medany -nostdlib
CDEFS    := $(CDEFS) -DDBGENV=$(DBGENV) -DTOPPERS_$(DBGENV)_EXEC
LDFLAGS  := $(LDFLAGS) -nostdlib -nostartfiles

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o 

#
#  システムサービスに関する定義
#
STASK_DIR := $(STASK_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
STASK_ASMOBJS := $(STASK_ASMOBJS) embedded_head.o
STASK_COBJS := $(STASK_COBJS) hw_serial.o rp2350.o

#
#  リンカスクリプトの定義
#
ifeq ($(DBGENV),RAM)
LDSCRIPT = $(CPU)/$(SYS)/rp2350_ram.ld
else
LDSCRIPT = $(CPU)/$(SYS)/rp2350_rom.ld
endif

