#
#  @(#) $Id: Makefile.config,v 1.7 2001/10/19 13:56:51 honda Exp $
# 

#
#  Makefile のシステム依存部分（RSH3用）
#

#
#  マクロ定義
#  16MHz,40MHzどちらの水晶を差すかによって選択
#
SYS_CDEFS = -DCONFIG_16MHZ 
#SYS_CDEFS = -DCONFIG_40MHZ 

#
#  コンパイルフラグ
#  ビックエンディアン
#
SYS_CFLAGS = -mb

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x0C001000
DATA_START_ADDRESS=0x0C100000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld






