#
#  @(#) $Id: Makefile.config,v 1.1 2000/11/14 16:30:22 honda Exp $
# 

#
#  Makefile のシステム依存部分（RSH3用）
#

#
#  コンパイルフラグ
#  16MHz,40MHzどちらの水晶を差すかによって選択
#
#CFLAGS := $(CFLAGS) -DCONFIG_16MHZ
CFLAGS := $(CFLAGS) -DCONFIG_40MHZ

#
#  コンパイルフラグ
#  ビックエンディアン
#
CFLAGS := $(CFLAGS) -mb

LDFLAGS := $(LDFLAGS) 

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x0C001000
DATA_START_ADDRESS=0x0C100000



#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld






