#
#  @(#) $Id: Makefile.config,v 1.2 2001/02/23 18:39:20 honda Exp $
# 

#
#  Makefile のシステム依存部分（RSH3用）
#

#
#  コンパイルフラグ
#  16MHz,40MHzどちらの水晶を差すかによって選択
#
#CDFLAGS := $(CDFLAGS) -DCONFIG_16MHZ
CDFLAGS := $(CDFLAGS) -DCONFIG_40MHZ


#
#  コンパイルフラグ
#  ビックエンディアン
#
CFLAGS := $(CFLAGS) -mb

LDFLAGS := $(LDFLAGS) 

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS=0x0C001000
DATA_START_ADDRESS=0x0C100000



#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld






