#
#  @(#) $Id: Makefile.config,v 1.1 2000/11/14 14:44:16 hiro Exp $
# 

#
#	Makefile のターゲットシステム依存部（DVE68K/40用）
#

#
#  コンパイルフラグ
#
CFLAGS := $(CFLAGS) -msoft-float
LDFLAGS := $(LDFLAGS) -msoft-float

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS = 00010000
DATA_START_ADDRESS = 00100000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/m68kelf.ld
