#
#  @(#) $Id: Makefile.config,v 1.2 2001/09/25 15:13:45 hiro Exp $
# 

#
#	Makefile のターゲットシステム依存部（DVE68K/40用）
#

#
#  コンパイルフラグ
#
SYS_CFLAGS = -msoft-float
SYS_LDFLAGS = -msoft-float

#
#  各セグメントの開始アドレスの定義
#
TEXT_START_ADDRESS = 00010000
DATA_START_ADDRESS = 00100000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/m68kelf.ld
