#
#  @(#) $Id: Makefile.config,v 1.1 2001/11/05 13:34:25 honda Exp $
# 

#
#  Makefile のシステム依存部分（MS7709ASE01用）
#

#
# マクロ定義
# 
SYS_CDEFS =

#
#  コンパイルフラグ
#  ビッグエンディアン
#
SYS_CFLAGS = -mb

#
#  各セグメントの開始アドレスの定義
#
ifeq ($(GDB_STUB),true)
     TEXT_START_ADDRESS=0x08003000
     DATA_START_ADDRESS=0x08103000
else
ifeq ($(PARTNER_J),true)
     TEXT_START_ADDRESS=0xa8000000
     DATA_START_ADDRESS=0xa8100000
endif
endif

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld





