#
#  @(#) $Id: Makefile.config,v 1.1 2025/11/08 14:53:01 roi Exp $
# 

#
#  Makefile のシステム依存部分（Raspberry Pi Pico2用）
#

#
#  実行環境の定義
#
ifeq ($(DBGENV),GDB_STUB)
DBGENV = RAM
endif
ifeq ($(DBGENV),)
DBGENV = RAM
endif

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=cortex-m33 -mthumb -mlittle-endian -nostartfiles
CDEFS    := $(CDEFS) -DDBGENV=$(DBGENV) -DTOPPERS_$(DBGENV)_EXEC
LDFLAGS  := $(LDFLAGS) -mlittle-endian -nostartfiles

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) 
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o hw_interpro.o

#
#  システムサービスに関する定義
#
STASK_DIR := $(STASK_DIR):$(CONFIGDIR)/$(CPU)/$(SYS)
STASK_ASMOBJS := $(STASK_ASMOBJS) embedded_head.o
STASK_COBJS := $(STASK_COBJS) hw_serial.o rp2350.o

#
#  FPUの方式
#
#FPU_USAGE := FPCCR_NO_PRESERV
#FPU_USAGE := FPCCR_NO_LAZYSTACKING
FPU_USAGE := FPCCR_LAZYSTACKING

#
#  リンカスクリプトの定義
#
ifeq ($(DBGENV),RAM)
LDSCRIPT = $(CPU)/$(SYS)/rp2350_ram.ld
else
LDSCRIPT = $(CPU)/$(SYS)/rp2350_rom.ld
endif

