#
#  @(#) $Id: Makefile.config,v 1.2 2001/10/22 02:16:43 imai Exp $
#

#
#  Makefile のシステム依存部分（常盤商行SH1/CPUB用）
#

#
#  コンパイルフラグ
#
#　　ICEを用いる場合
#  　　・実機とICEのクロック周波数の違いを吸収
#  　　・dataセグメントの扱いに不具合のある一部のICEに対応
#　　　　（アドレスLMAにダウンロードすべきデータをVMAに
#　　　　　ダウンロードしてしまう）
#
#　　　make USE_ICE=true
#　　とする。

ifeq ($(USE_ICE),true)
    SYS_CDEFS = -DCONFIG_20MHZ -DUSE_ICE
else
    SYS_CDEFS = -DCONFIG_16MHZ
endif


#
#  各セグメントの開始アドレスの定義
#
# テキストセクションの先頭番地
# ベクタテーブルの後ろ
TEXT_START_ADDRESS=0x00000400

# RAM領域の先頭アドレス(エリア７：内蔵RAM)
DATA_START_ADDRESS=0x0f000000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/shelf.ld
