#
#		Makefileのプロセッサ依存部（Cortex-M0/M0+用）
#

#
#  開発環境名の定義
#
MARCH = armv6m

#
#  ターゲットアーキテクチャの定義
#
TARGET = arm-none-eabi

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU) 
COPTS := $(COPTS) -O2 
CDEFS := $(CDEFS) -DOMIT_VXCFG_INT
LDFLAGS := $(LDFLAGS) -nostdlib -nostartfiles

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
        -O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
