#
#  @(#) $Id: Makefile.config,v 1.2 2000/11/14 16:50:52 takayuki Exp $
# 

#
#	Makefile のプロセッサ依存部（68040用）
#

#
#  コンパイルフラグ
#
CFLAGS := -g

#
#  ディレクトリの定義
#
#TOPDIR = /usr/local/$(ARCH)
#LIBDIR = $(TOPDIR)/lib
#SFLIBDIR = $(LIBDIR)/msoft-float
#INCDIR = $(TOPDIR)/include

#
#  コンパイラドライバの定義
#
CC = gcc
AS = gas
LD = ld
AR = ar
NM = nm
RANLIB  = ranlib
OBJCOPY = objcopy.exe
OBJDUMP = objdump
