#
#  Makefile のシステム依存部分（VR5500, RTE-VR5500-CB用）
#

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS) \
			-I$(SRCDIR)/pdic/simple_sio
COPTS := $(COPTS) -msoft-float -mgp32
LDFLAGS := $(LDFLAGS)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS) \
				:$(SRCDIR)/pdic/simple_sio
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o tl16pir552.o
# tl16pir552.o が、ボード依存の個所

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/vr5500elf.ld

