# 
#  @(#) $Id: Makefile.config,v 1.14 2007/07/27 11:28:44 honda Exp $
#
 
TARGET ?= lm32-elf

INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)
COPTS    := $(COPTS) -g -O2
#LDFLAGS  := $(LDFLAGS)

CFLAGS = $(COPTS) $(CDEFS) $(INCLUDES)

#LDSCRIPT = $(CPU)/lm32elf.ld

KERNEL_DIR     := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) cpu_config.o

#COPTS   := $(COPTS) -mmultiply-enabled -mbarrel-shift-enabled -mdivide-enabled -msign-extend-enabled -ffunction-sections -D__lm32__

START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) -O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
