#
#  @(#) $Id: Makefile.config,v 1.3 2005/11/24 12:41:23 honda Exp $
# 

#
#	Makefile のプロセッサ依存部（M16C用）
#

#
#  共通コンパイルオプション
#
CDEFS := $(CDEFS)
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)\$(CPU)-$(TOOL) \
		-I$(CONFIGDIR)\$(CPU)
COPTS := $(COPTS) -dir . -silent
LDFLAGS := $(LDFLAGS) -. -MSL -G
ifdef LIBS
	LIBS := $(LIBS),nc30lib
else
	LIBS := nc30lib
endif

KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)\$(CPU)-$(TOOL)
KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)\$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.r30
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.r30

#OMIT_MAKEOFFSET = TRUE

CC = nc30
AS = as30
AR = lb30
LD = ln30
CPP = C:\Hew\Tools\Renesas\nc30wa\v545r01\lib30\cpp30
OBJCOPY = lmc30

# スタートアップモジュールのオブジェクトファイル名
START_OBJS = start.r30

# スタートアップモジュールのコンパイルルール
$(START_OBJS): %.r30: %.a30 m16cvec.inc
	$(AS) $(ASMFLAGS) -DRAMEND=$(RAMEND)h:MON=$(MON) $(<D)\$(<F)

# スタートアップモジュールの依存関係作成ルール(何もしない)
$(START_OBJS:.r30=.d): %.d: %.a30

# アセンブリ言語ファイルの依存関係
cpu_support.r30: cpu_support.a30 offset.inc
