#
#  @(#) $Id: Makefile.config,v 1.6 2003/12/01 06:29:15 honda Exp $
# 

#
#  Makefile のシステム依存部分（Excalibur-ARM用）
#

#
#  コンパイルフラグ
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS)
COPTS    := $(COPTS) -mcpu=arm9tdmi -Wa,--gstabs
LDFLAGS  := $(LDFLAGS) -mcpu=arm9tdmi  -N

#
# カーネルに関する定義
#
KERNEL_DIR     := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS   := $(KERNEL_COBJS) sys_config.o excalibur.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/excalibur.ld


#
#  ターゲットボード依存の定義
#

#  KZ-ARM9EX用
COPTS   := $(COPTS) -DKZ_ARM9EX -mlittle-endian   
LDFLAGS := $(LDFLAGS) -mlittle-endian 
TEXT_START_ADDRESS=0x0000003c
DATA_START_ADDRESS=0x00010000
